### ISSUE TITLE
fix issues found in current buildd logs for grpn

### ISSUE THREAD

**Issue by getreu** [getreu/grpn#11]
#  buildd log scanner -- issues 

 [buildd log scanner -- issues in package grpn -- Debian Quality Assurance](https://qa.debian.org/bls/packages/g/grpn.html)

Snapshot of 20181020:

*    E pointer-trouble-at-implicit process_input.c:80
*    W dpkg-buildflags-missing CPPFLAGS 23 (of 23), CFLAGS 23 (of 23) missing (hppa, ia64)
*    W dpkg-buildflags-missing CPPFLAGS 23 (of 23), CFLAGS 23 (of 23), LDFLAGS 1 (of 1) missing 
*    W implicit-declaration callback_buttons.c:67 
*    W implicit-declaration funcs.c:840
*    W implicit-declaration main.c:93
*    W implicit-declaration process_input.c:193 

# Lintian Report

[Lintian Report for Wartan Hachaturow](https://lintian.debian.org/maintainer/wart@debian.org.html#grpn)

**Comment by utopiabound** [comment]
I've browsed through the issues listed above, and as far as I can tell between #12 and changes from 1.4.1 and 1.5.1 all the above warning/errors should be resolved.

**Comment by getreu** [comment]
In general PRs are easier to review when you have 1 PR per issue. Your PR looks Ok to me.
Thank you.
