### ISSUE TITLE
Wrong results after radix conversion

### ISSUE THREAD

**Issue by Napf** [getreu/grpn#6]
Using grpn 1.4.0 with default settings. Enter the following:
54321 <enter>
23 /
2361 -
23 *
Result is "18" (as it should be). Now type "hex".
Display now reads 0x11, but should read 0x12.
Going back to "'dec", display reads "18" again.
The same problem exists for "bin" (displays "10001", should be "10010") and "oct" (displays "021", should be "022").

**Comment by getreu** [comment]
This is a floating-point arithmetic rounding error. grpn uses standard glibc and floats. HEX and BIN only consider the integer part of the number. The number you are converting is shown as 18 but in memory it is 17.999999.... thus you get 0x11 instead of 0x12. 

try:
54321
23 /
2361 -
23 *
18 - 
shows: -3.63797880709e-12

**Comment by Napf** [comment]
This confirms my assumption that it is an internal rounding error, but unfortunately the explanation doesn't resolve the issue -- if the display actually shows 18 (and not 17.999...), I'd expect the hex conversion to yield 0x12. 
Out of curiosity, I have tried this on a few other calculators: several Casio calculators from different decades all display slightly less than 18, the same goes for Python and Perl. RealCalc (on Android) has the same problem as grpn. Only KCalc (Trinity) gets it right and comes out with exactly 18 (subtract 18, and you'll end up with 0) and accordingly converts to 0x12.

To resolve this issue, is there a way to detect that the displayed integer part is different from the internal one, and do the radix conversion with the displayed value instead?

**Comment by getreu** [comment]
> This confirms my assumption that it is an internal rounding error, but unfortunately the explanation doesn't resolve the issue -- if the display actually shows 18 (and not 17.999...), I'd expect the hex conversion to yield 0x12.

This is a design choice. The internal memory holds some more digits than the displayed float shows.
Hex and bin mode does not change the internal representation of the float, it just takes the integer part and displays it. Decimal fractions are _not_ supported when displaying in hex or bin.

> To resolve this issue, is there a way to detect that the displayed integer part is different from the internal one, and do the radix conversion with the displayed value instead?

grpn is not so good in integer arithmetic: some basic functions are missing, e.g.
`div, floor, ceiling, inv`. First 3 are easy to implement, the latter not.

> To resolve this issue, is there a way to detect that the displayed integer part is different from the internal one, and do the radix conversion with the displayed value instead?

In your case the `floor` function would help, but it is not implemented yet.
